Configure repository
SpineEventEngine/firebase-storage pull request #1
Opened 2018-01-03 16:42 UTC by dmdashenkov

In this PR we configure this repository in consistency with all other Spine Event Engine repositories.

2018-01-03 17:33 UTC, dmdashenkov commented
@armiol, PTAL.

2018-01-04 10:10 UTC, armiol commented
As discussed, let's make this library JDK7-compliant.

2018-01-04 12:02 UTC, dmdashenkov commented
@armiol, PTAL again.

2018-01-04 12:25 UTC, armiol requested changes
@dmdashenkov please see my comments.

2018-01-04 12:25 UTC, armiol commented on build.gradle
> +        testCompile("io.spine:spine-testutil-client:${spineVersion}") {
This dependency looks redundant.

2018-01-04 12:25 UTC, armiol commented on build.gradle
> +        compile (group: 'io.spine', name: 'spine-testutil-server', version: spineVersion)
This dependency looks redundant.

2018-01-04 12:25 UTC, armiol commented on build.gradle
> +            // We are using JUnit 5.x instead of 4.x dependency of Spine testing framework.
Are we using JUnit5 with JDK7? I don't think so.
  
Same below. For several more times.

2018-01-04 12:25 UTC, armiol commented on .travis.yml
> +  - oraclejdk8
Each time we talk about that. Can we have a comment explaining why JDK7-compatible project is built in JDK8-powered environment?

2018-01-04 12:58 UTC, dmdashenkov commented
@armiol, PTAL again.

2018-01-04 16:08 UTC, armiol approved these changes
@dmdashenkov LGTM. I also expect to see publishing configured somehow.

2018-01-04 16:09 UTC, merged