Release `1.0.0-pre4`
SpineEventEngine/firebase-storage pull request #7
Opened 2019-02-12 14:59 UTC by dmitrykuzmin

This PR releases `1.0.0-pre4` version of this library.

The code base is brought into correspondence with the latest Spine as well as the new [event subscriptions](https://github.com/SpineEventEngine/core-java/pull/961) functionality.

Gradle version is updated to 5.2.

2019-02-12 15:03 UTC, dmitrykuzmin commented
@armiol PTAL.

2019-02-12 17:19 UTC, armiol reviewed
@dmitrykuzmin can you please apply PMD rules and address the issues?
(see https://github.com/SpineEventEngine/base/pull/325/commits/7c89593e251570288c16293b5288d427a813e7c4)

2019-02-12 17:24 UTC, armiol requested changes
@dmitrykuzmin and also please see my comments.

2019-02-12 17:24 UTC, armiol commented on firebase-mirror/src/main/java/io/spine/server/firebase/FirestoreSubscriptionPublisher.java
> +abstract class FirestoreSubscriptionPublisher<U> implements Logging {
Isn't it just `FirestorePublisher`? And `U` seems to be just an "update" we publish.

2019-02-12 17:24 UTC, armiol commented on firebase-mirror/src/main/java/io/spine/server/firebase/EventSubscriptionPublisher.java
> +final class EventSubscriptionPublisher extends FirestoreSubscriptionPublisher<Event> {
If `FirestoreSubscriptionPublisher` is just `FirestorePublisher` (see my comment below), this is `EventPublisher`.

2019-02-12 17:24 UTC, armiol commented on firebase-mirror/src/main/java/io/spine/server/firebase/EventUpdateObserver.java
> +final class EventUpdateObserver extends SubscriptionUpdateObserver<Event> {
And this is `EventObserver`, which extends `UpdateObserver`.

2019-02-12 18:01 UTC, dmitrykuzmin commented
@armiol PTAL.

2019-02-15 19:29 UTC, armiol approved these changes

2019-02-15 19:30 UTC, merged